palette:
  top: '#5F1761'
  bottom: '#5F1761'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#5F1761'
logo: 'public://color/bartik-46fe9906/logo.svg'
stylesheets:
  - 'public://color/bartik-46fe9906/colors.css'
files:
  - 'public://color/bartik-46fe9906/logo.svg'
  - 'public://color/bartik-46fe9906/colors.css'
